fenacon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.flatpages.views import (ActingDetailView, InstitutionalDetailView,
                                  AnnounceView)
from apps.office.views import SyndicateListView, OfficeListView
from apps.website.views import HomeView, SearchView
from apps.website.api import (api_root, NewsListAPI, NewsCategoryListAPI,
                              EventListAPI, PressClippingListAPI,
                              CreateUserAPI, FenaconMidiaListAPI,
                              SyndicateListAPI, OfficeListAPI, AboutUsListAPI,
                              ObtainAuthToken, MagazineListAPI,
                              PressClippingAPI, NewsDetailAPI)
from fenacon import settings

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^', include('apps.website.urls')),
    url(r'^multimidia/', include('apps.multimidia.urls')),
    url(r'^busca/', SearchView.as_view(), name='search'),
    url(r'^sindicatos-filiados/', SyndicateListView.as_view(), name='syndicate'),
    # url(r'^escritorios/', OfficeListView.as_view(), name='offices'),
    url(r'^atuacao/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', ActingDetailView.as_view(), name='acting_detail'),
    url(r'^institucional/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', InstitutionalDetailView.as_view(), name='institutional_detail'),
    url(r'^publicacoes/(?P<slug>[\w_-]+)/', AnnounceView.as_view(), name='announce_detail'),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += [
    url(r'^api/$', api_root),
    url(r'^api/token-auth/', ObtainAuthToken.as_view()),
    url(r'^api/news/$', NewsListAPI.as_view(), name='news_list_api'),
    url(r'^api/news/(?P<pk>\d+)/?$', NewsDetailAPI.as_view(),
        name='news_detail_api'),
    url(r'^api/events/$', EventListAPI.as_view(), name='event_list_api'),
    url(r'^api/category/$', NewsCategoryListAPI.as_view(),
        name='category_list_api'),
    url(r'^api/user/create/$', CreateUserAPI.as_view(),
        name='user_create_api'),
    url(r'^api/press-clipping/$', PressClippingListAPI.as_view(),
        name='pressclipping_list_api'),
    url(r'^api/press-clipping/(?P<pk>\d+)/?$', PressClippingAPI.as_view(),
        name='pressclipping_detail_api'),
    url(r'^api/fenacon-midia/$', FenaconMidiaListAPI.as_view(),
        name='fenaconmidia_list_api'),
    url(r'^api/syndicate/$', SyndicateListAPI.as_view(),
        name='syndicate_list_api'),
    url(r'^api/office/$', OfficeListAPI.as_view(),
        name='office_list_api'),
    url(r'^api/about-us/$', AboutUsListAPI.as_view(),
        name='aboutus_list_api'),
    url(r'^api/magazine/$', MagazineListAPI.as_view(),
        name='magazine_list_api'),
]

urlpatterns += patterns('',
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^ckeditor/', include('ckeditor_uploader.urls')),
)

admin.site.site_header = 'FENACON Website'

apps/office/models.py
# coding=utf-8
from datetime import datetime
from csvImporter.model import CsvDbModel
from django.db import models
from apps.accounts.models import User
from django.db.models.signals import post_save

UF_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)

REGION = {('norte', 'Norte'),
          ('nordeste', 'Nordeste'),
          ('centro-oeste', 'Centro-Oeste'),
          ('sudeste', 'Sudeste'),
          ('sul', 'Sul')}


class Syndicate(models.Model):
    name = models.CharField('Nome', max_length=150, help_text="Exemplo: SESCON - Estado")
    president = models.CharField('Presidente', max_length=150)
    address = models.CharField('Endereço', max_length=150)
    region = models.CharField('Região', max_length=50, choices=REGION)
    state = models.CharField('Estado', max_length=50, choices=UF_CHOICES)
    city = models.CharField('Cidade', max_length=100)
    cep = models.CharField('CEP', max_length=50)
    phone = models.CharField('Telefone', max_length=50)
    email = models.EmailField()
    page = models.URLField("Home page", blank=True, null=True)
    code = models.CharField("Código Sindical", max_length=100)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(verbose_name='Data do Cadastro', blank=True, default=datetime.now)
    user = models.ForeignKey(User, verbose_name='Usuário')

    class Meta:
        verbose_name = u'Sindicato'
        verbose_name_plural = u'Sindicatos'

    def __unicode__(self):
        return self.name


class Office(models.Model):
    cnpj = models.CharField(max_length=20)
    company_name = models.CharField('Razão social', max_length=150)
    patio_type = models.CharField('Tipo de logradouro', max_length=150, blank=True, null=True)
    address = models.CharField('Endereço', max_length=150)
    number = models.CharField('Número', max_length=10, blank=True, null=True)
    complement = models.CharField('Complemento', max_length=150, blank=True, null=True)
    neighborhood = models.CharField('Bairro', max_length=100, blank=True, null=True)
    city = models.CharField('Cidade', max_length=100, blank=True, null=True)
    state = models.CharField('Estado', max_length=50, choices=UF_CHOICES, blank=True, null=True)
    cep = models.CharField(max_length=200, blank=True, null=True)
    emails = models.CharField(max_length=200, blank=True, null=True)
    phone = models.CharField('Telefone', max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = u'Escritório'
        verbose_name_plural = u'Escritórios'

    def __unicode__(self):
        return self.company_name


class OfficeCsvModel(CsvDbModel):

    class Meta:
        delimiter = ";"
        dbModel = Office


class FileToImport(models.Model):
    file = models.FileField('Arquivo', upload_to='uploads/escritorios/')
    created_at = models.DateTimeField(verbose_name='Data do Cadastro', blank=True, default=datetime.now)

    class Meta:
        verbose_name = u'Arquivo para importação'
        verbose_name_plural = u'Arquivos para importação'

    def __unicode__(self):
        return u'%s' % str(self.file).split('/')[-1]


def crete_offices(sender, instance, **kwargs):
    from django.conf import settings
    office_csv_list = OfficeCsvModel.import_data(data=open(settings.MEDIA_ROOT + '/' + str(instance.file)))
    for row in range(0, len(office_csv_list)):
        office = Office()
        office.cnpj = office_csv_list[row].cnpj
        office.company_name = office_csv_list[row].company_name
        office.patio_type = office_csv_list[row].patio_type
        office.address = office_csv_list[row].address
        office.number = office_csv_list[row].number
        office.complement = office_csv_list[row].complement
        office.neighborhood = office_csv_list[row].neighborhood
        office.city = office_csv_list[row].city
        office.state = office_csv_list[row].state
        office.cep = office_csv_list[row].cep
        office.emails = office_csv_list[row].emails
        office.phone = office_csv_list[row].phone
# register the signal
post_save.connect(crete_offices, sender=FileToImport)

apps/office/forms.py
# -*- coding: utf-8 -*-
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.core.mail import send_mail
from apps.website.models import News, Event

UF_CHOICES = (
    ('', 'Selecione um estado'),
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)

REGION = {
    ('', 'Selecione uma região'),
    ('norte', 'Norte'),
    ('nordeste', 'Nordeste'),
    ('centro-oeste', 'Centro-Oeste'),
    ('sudeste', 'Sudeste'),
    ('sul', 'Sul')
}




class FormState(forms.Form):
    state = forms.ChoiceField(choices=sorted(UF_CHOICES, key=lambda x: x[0]), required=True)


class FormSyndicate(forms.Form):
    region = forms.ChoiceField(choices=sorted(REGION, key=lambda x: x[0]), required=True)
    state = forms.ChoiceField(choices=sorted(UF_CHOICES, key=lambda x: x[0]), required=True)


class FormOffice(forms.Form):
    state = forms.ChoiceField(choices=sorted(UF_CHOICES, key=lambda x: x[0]), required=True)
    city = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Cidade'}))
    neighborhood = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Bairro'}))

apps/office/views.py
# coding=utf-8
from django.views.generic import ListView
from import_export import resources, fields
from apps.office.forms import FormSyndicate, FormOffice
from apps.office.models import Syndicate, Office


class SyndicateListView(ListView):
    model = Syndicate
    template_name = 'office/sindicatos.html'

    def get_context_data(self, **kwargs):
        context = super(SyndicateListView, self).get_context_data(**kwargs)
        context['form'] = FormSyndicate()
        return context

    def get_queryset(self):
        region = self.request.GET.get('region')
        state = self.request.GET.get('state')
        object_list = Syndicate.objects.filter(status=True).order_by('state')
        if region:
            object_list = object_list.filter(region=region)
        if state:
            object_list = object_list.filter(state=state)
        return object_list


class OfficeListView(ListView):
    model = Office
    template_name = 'office/escritorios.html'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super(OfficeListView, self).get_context_data(**kwargs)
        context['form'] = FormOffice()
        return context

    def get_queryset(self):
        city = self.request.GET.get('city')
        neighborhood = self.request.GET.get('neighborhood')
        state = self.request.GET.get('state')
        object_list = Office.objects.none()
        if city or neighborhood or state:
            object_list = Office.objects.all().order_by('state')
            if city:
                object_list = object_list.filter(city__icontains=city)
            if neighborhood:
                object_list = object_list.filter(neighborhood__icontains=neighborhood)
            if state:
                object_list = object_list.filter(state=state)
        return object_list


class OfficeResource(resources.ModelResource):
    # cnpj = fields.Field(column_name='CNPJ')
    # company_name = fields.Field(column_name='Razão')
    # patio_type = fields.Field(column_name='Tipo Logadouro')
    # address = fields.Field(column_name='Endereço')
    # number = fields.Field(column_name='Número')
    # complement = fields.Field(column_name='Complemento')
    # neighborhood = fields.Field(column_name='Bairro')
    # city = fields.Field(column_name='Cidade')
    # state = fields.Field(column_name='Estado')
    # emails = fields.Field(column_name='Email')
    # phone = fields.Field(column_name='Telefone')

    class Meta:
        model = Office
        # import_id_fields = ['id']
        # fields = ('cnpj', 'company_name', 'patio_type', 'address', 'number', 'complement', 'neighborhood', 'city',
        #           'state', 'emails', 'phone')

    def get_instance(self, instance_loader, row):
        return False

templates/office/escritorios.html
{% extends 'elements/base.html' %}
{% block title %}Escritórios - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">Escritórios</h2>
            </div>
        </div>

        <div class="row">
            <form action="{% url 'offices' %}" method="get" class="filter-form" data-abide>
                <div class="large-3 medium-3 small-12 columns">
                    <select id="id_state" name="state">
                    {% for x,y in form.fields.state.choices %}
                        <option value="{{ x }}"{% if request.GET.state == x %} selected{% endif %}>{{ y }}</option>
                    {% endfor %}
                    </select>
                </div>

                <div class="large-3 medium-3 columns">
                    <input id="id_city" name="city" placeholder="Cidade" type="text" {% if request.GET.city %}value="{{ request.GET.city }}"{% endif %}>
                </div>

                 <div class="large-3 medium-3 columns">
                    <input id="id_neighborhood" name="neighborhood" placeholder="Bairro" type="text" {% if request.GET.neighborhood %}value="{{ request.GET.neighborhood }}"{% endif %}>
                </div>

                <div class="large-3 medium-3 small-12 columns">
                    <button type="submit" class="button small expand round">Pesquisar</button>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="large-12 medium-12 small-12 columns">
                <ul class="list-result-office small-block-grid-1 medium-block-grid-1 large-block-grid-2">
                    {% for office in object_list %}
                    <li>
                        <div class="item-office">
                            <h5 class="estado">{{ office.company_name }}</h5>
                            <p>End.: {% if office.patio_type %}{{ office.patio_type }} {% endif %}{{ office.address }}{% if office.number %}, Número {{ office.number }}{% endif %}</p>
                            {% if office.complement %}<p>Complemento: {{ office.complement }}</p>{% endif %}
                            {% if office.neighborhood %}<p>Bairro: {{ office.neighborhood }}</p>{% endif %}
                            {% if office.city %}<p>Cidade: {{ office.city }}</p>{% endif %}
                            <p>UF: {{ office.state }}</p>
                            {% if office.phone %}<p>Telefone: {{ office.phone }}</p>{% endif %}
                            {% if office.emails %}<p>Email: {{ office.emails }}</p>{% endif %}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {% if is_paginated %}
        <hr>
        <div class="row">
            <div class="large-10 large-centered medium-10 medium-centered small-12 small-centered columns">
                <ul class="pagination pages">
                    {% if page_obj.has_previous %}
                        <li class="arrow"><a href="?page=1{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">◀◀</a></li>
                        <li class="arrow"><a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">◀</a></li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% ifequal num page_obj.number %}
                            <li><a href="" class="current">{{ num }}</a></li>
                        {% else %}
                            {% if num <= page_obj.number|add:2 and num >= page_obj.number|add:-2 %}
                                <li><a href="?page={{ num }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ num }}</a></li>
                            {% endif %}
                        {% endifequal %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="arrow "><a href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">▶</a></li>
                        <li class="arrow "><a href="?page={{ page_obj.paginator.num_pages }}{% for key, value in request.GET.iteritems %}{% if not key == 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">▶▶</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endif %}
    </div>
</section>

{% endblock %}
{% block extrajs %}
<script type="text/javascript">
    function disableselect(e){
        return false
    }
    function reEnable(){
        return true
    }
    document.onselectstart=new Function ("return false")
    if (window.sidebar){
        document.onmousedown=disableselect
        document.onclick=reEnable
    }
</script>
{% endblock %}

templates/office/sindicatos.html
{% extends 'elements/base.html' %}
{% block title %}Sindicatos - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">Sindicatos filiados</h2>
                <p class="section-subtitle">
                    O Sistema Fenacon representa 37 Sindicatos das Empresas de Serviços Contábeis e das Empresas de Assessoramento, Perícias, Informações e Pesquisas.
                </p>
            </div>
        </div>

        <div class="row">
            <form action="{% url 'syndicate' %}" class="filter-form" data-abide method="get">
                <div class="large-6 medium-6 small-12 columns">
                    <select id="id_region" name="region">
                    {% for x,y in form.fields.region.choices %}
                        <option value="{{ x }}"{% if request.GET.region == x %} selected{% endif %}>{{ y }}</option>
                    {% endfor %}
                    </select>
                </div>
                <div class="large-6 medium-6 small-12 columns">
                    <select id="id_state" name="state">
                    {% for x,y in form.fields.state.choices %}
                        <option value="{{ x }}"{% if request.GET.state == x %} selected{% endif %}>{{ y }}</option>
                    {% endfor %}
                    </select>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="large-12 medium-12 small-12 columns">
                <ul class="list-result-office small-block-grid-1 medium-block-grid-1 large-block-grid-2">
                    {% for object in object_list %}
                    <li>
                        <div class="item-office">
                            <h5 class="estado">{{ object.get_state_display|upper }}</h5>
                            <h5>{{ object.name }}</h5>
                            <h5>Presidente: {{ object.president }}</h5>
                            <p>End.: {{ object.address }}</p>
                            <p>CEP: {{ object.cep }} – {{ object.city }}/{{ object.state|upper }} - Tel.: {{ object.phone }}</p>
                            <p>E-mail: <a href="mailto:{{ object.email }}">{{ object.email }}</a></p>
                            <p>Home page: <a href="{{ object.page }}">{{ object.page }}</a></p>
                            <p>Cód. Sindical: {{ object.code }}</p>
                        </div>
                    </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block extrajs %}
    <script type="text/javascript">
        $(function() {
            $('#id_region').change(function() {
                $('#id_state').val('');
                this.form.submit();
            });
            $('#id_state').change(function() {
                $('#id_region').val('');
                this.form.submit();
            });
        });
    </script>
{% endblock %}