apps/website/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from apps.multimidia.views import MagazineListView, PublicationListView
from apps.website.views import NewsListView, EventListView, NewsDetailView, ContactView, EventDetailView, \
    FenaconMidiaListView, PressClippingListView, FenaconMidiaDetailView, PressClippingDetailView, ContestSubscriberCreateView
from apps.website.api import PromotionSubscriberListAPI


urlpatterns = patterns('',
    url(r'^noticias/$', NewsListView.as_view(), name='news_list'),
    url(r'^noticias/(?P<slug>[\w_-]+)-(?P<pk>\d+)/$', NewsDetailView.as_view(), name='news_detail'),
    url(r'^noticias/press-clipping/$', PressClippingListView.as_view(), name='pressclipping_list'),
    url(r'^noticias/press-clipping/(?P<slug>[\w_-]+)-(?P<pk>\d+)/$', PressClippingDetailView.as_view(), name='pressclipping_detail'),
    url(r'^noticias/fenacon-na-midia/$', FenaconMidiaListView.as_view(), name='fenaconmidia_list'),
    url(r'^noticias/fenacon-na-midia/(?P<slug>[\w_-]+)-(?P<pk>\d+)/$', FenaconMidiaDetailView.as_view(), name='fenaconmidia_detail'),
    url(r'^eventos/(?P<slug>[\w_-]+)-(?P<pk>\d+)/$', EventDetailView.as_view(), name='event_detail'),
    url(r'^eventos/$', EventListView.as_view(), name='event_list'),
    # url(r'^contato/$', ContactView.as_view(), name='contact'),
    url(r'^concurso/$',  ContestSubscriberCreateView.as_view(), name='concurso'),
    url(r'^api/promocao/participantes/$', PromotionSubscriberListAPI.as_view(),
        name='promotion_subscriber_api'),
    url(r'^location/$',  'apps.website.views.get_location', name='location'),
)

fenacon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.flatpages.views import (ActingDetailView, InstitutionalDetailView,
                                  AnnounceView)
from apps.office.views import SyndicateListView, OfficeListView
from apps.website.views import HomeView, SearchView
from apps.website.api import (api_root, NewsListAPI, NewsCategoryListAPI,
                              EventListAPI, PressClippingListAPI,
                              CreateUserAPI, FenaconMidiaListAPI,
                              SyndicateListAPI, OfficeListAPI, AboutUsListAPI,
                              ObtainAuthToken, MagazineListAPI,
                              PressClippingAPI, NewsDetailAPI)
from fenacon import settings

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^', include('apps.website.urls')),
    url(r'^multimidia/', include('apps.multimidia.urls')),
    url(r'^busca/', SearchView.as_view(), name='search'),
    url(r'^sindicatos-filiados/', SyndicateListView.as_view(), name='syndicate'),
    # url(r'^escritorios/', OfficeListView.as_view(), name='offices'),
    url(r'^atuacao/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', ActingDetailView.as_view(), name='acting_detail'),
    url(r'^institucional/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', InstitutionalDetailView.as_view(), name='institutional_detail'),
    url(r'^publicacoes/(?P<slug>[\w_-]+)/', AnnounceView.as_view(), name='announce_detail'),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += [
    url(r'^api/$', api_root),
    url(r'^api/token-auth/', ObtainAuthToken.as_view()),
    url(r'^api/news/$', NewsListAPI.as_view(), name='news_list_api'),
    url(r'^api/news/(?P<pk>\d+)/?$', NewsDetailAPI.as_view(),
        name='news_detail_api'),
    url(r'^api/events/$', EventListAPI.as_view(), name='event_list_api'),
    url(r'^api/category/$', NewsCategoryListAPI.as_view(),
        name='category_list_api'),
    url(r'^api/user/create/$', CreateUserAPI.as_view(),
        name='user_create_api'),
    url(r'^api/press-clipping/$', PressClippingListAPI.as_view(),
        name='pressclipping_list_api'),
    url(r'^api/press-clipping/(?P<pk>\d+)/?$', PressClippingAPI.as_view(),
        name='pressclipping_detail_api'),
    url(r'^api/fenacon-midia/$', FenaconMidiaListAPI.as_view(),
        name='fenaconmidia_list_api'),
    url(r'^api/syndicate/$', SyndicateListAPI.as_view(),
        name='syndicate_list_api'),
    url(r'^api/office/$', OfficeListAPI.as_view(),
        name='office_list_api'),
    url(r'^api/about-us/$', AboutUsListAPI.as_view(),
        name='aboutus_list_api'),
    url(r'^api/magazine/$', MagazineListAPI.as_view(),
        name='magazine_list_api'),
]

urlpatterns += patterns('',
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^ckeditor/', include('ckeditor_uploader.urls')),
)

admin.site.site_header = 'FENACON Website'

apps/website/models.py
# coding=utf-8
from datetime import datetime
from apps.accounts.models import User
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
from ckeditor_uploader.fields import RichTextUploadingField
import requests

REGION = {('norte', 'Norte'),
          ('nordeste', 'Nordeste'),
          ('centro-oeste', 'Centro-Oeste'),
          ('sudeste', 'Sudeste'),
          ('sul', 'Sul')}

UF_CHOICES = (
    ('', 'Nacional'),
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)


class SocialNetwork(models.Model):
    facebook = models.URLField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    youtube = models.URLField(null=True, blank=True)
    telefax = models.CharField(null=True, blank=True, max_length=30)
    address = models.CharField('Endereço FENACON', null=True, blank=True, max_length=200)
    cep = models.CharField('CEP da FENACON', null=True, blank=True, max_length=200)
    address_imprensa = models.CharField('Endereço Assessoria', null=True, blank=True, max_length=200)
    cep_imprensa = models.CharField('CEP Assessoria', null=True, blank=True, max_length=200)
    phone = models.CharField('Telefones Assessoria', null=True, blank=True, max_length=30)
    email = models.EmailField("Email da asessoria de impresa", null=True, blank=True)

    def __unicode__(self):
        return 'Contato FENACON'

    class Meta:
        verbose_name = "Contato"
        verbose_name_plural = "Contato"


class Banner(models.Model):
    photo = models.ImageField('Foto', upload_to='uploads/banner/', blank=True, null=True, help_text="Dimensões 870x135px")
    link = models.URLField(help_text="Endereço da página", blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='Data do Cadastro', blank=True, default=datetime.now)
    start_at = models.DateTimeField(verbose_name='Começa em', default=datetime.now)
    ends_in = models.DateTimeField(verbose_name='Términa em')
    user = models.ForeignKey(User, verbose_name='Usuário')
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'

    def __unicode__(self):
        return u'%s' % str(self.photo).split('/')[-1]


class Institute(models.Model):
    name = models.CharField("Nome", max_length=90)
    description = models.CharField("Descrição", max_length=140)
    link = models.URLField(help_text="Endereço da página")
    featured_image = models.ImageField("Imagem", upload_to='uploads/instituto/%Y/%m/', help_text="Dimensões 275x70px")
    status = models.BooleanField(verbose_name='Ativo?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver este instituição.")
    user = models.ForeignKey(User, verbose_name='Usuário')

    class Meta:
        verbose_name = u'Instituto Fenacon'
        verbose_name_plural = u'Institutos Fenacon'

    def __unicode__(self):
        return self.name


class ContributionGuide(models.Model):
    link = models.URLField(help_text="Endereço da página")
    status = models.BooleanField(verbose_name='Ativo?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver este instituição.")

    class Meta:
        verbose_name = u'Guia de contribuição sindical'
        verbose_name_plural = u'Guia de contribuição sindical'

    def __unicode__(self):
        return self.link


class Event(models.Model):
    title = models.CharField("Título", max_length=90, help_text="Titulo do Evento")
    text = RichTextUploadingField(verbose_name="Texto", null=True, blank=True)
    slug = models.SlugField(max_length=200, blank=True)
    city = models.CharField('Cidade/Estado', max_length=50, null=True, blank=True)
    local = models.CharField('Endereço', max_length=150)
    region = models.CharField('Região', max_length=50, choices=REGION, null=True, blank=True)
    credit = models.CharField("Crédito", max_length=30, blank=True, help_text="Creditos da foto.")
    featured_image = models.ImageField("Imagem Destaque", null=True, blank=True, upload_to='uploads/eventos/%Y/%m/', help_text="Dimensões 600x335 ou maior - JPEG")
    featured_big = ImageRatioField('featured_image', '600x335', verbose_name='Destaque Grande', help_text="Destaque princial na home.")
    featured_medium = ImageRatioField('featured_image', '470x180', verbose_name='Destaque Médio', help_text="Destaque secundário home.")
    featured_small = ImageRatioField('featured_image', '170x170', verbose_name='Destaque Pequeno', help_text="Imagem para listagem de eventos.")
    published_at = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)
    start_at = models.DateTimeField(verbose_name='Começa em', default=datetime.now)
    ends_in = models.DateTimeField(verbose_name='Términa em')
    status = models.BooleanField(verbose_name='Evento Ativo?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver este evento.")
    main_featured = models.BooleanField(verbose_name='Destaque principal', default=False, help_text="Coloca a notícia em destaque. Deve possuir imagem destaque.")
    featured = models.BooleanField(verbose_name='Destaque secundário', default=False, help_text="Coloca a notícia em destaque. Deve possuir imagem destaque.")
    user = models.ForeignKey(User, verbose_name='Usuário')


    class Meta:
        ordering = ('-published_at',)
        verbose_name = u'Evento'
        verbose_name_plural = u'Eventos'
        get_latest_by = 'published_at'

    @models.permalink
    def get_absolute_url(self):
        return ('event_detail', [self.slug, self.pk])

    def __unicode__(self):
        return self.title

    def get_featured_big(self):
        return get_thumbnailer(self.featured_image).get_thumbnail({'size': (600, 335), 'box': self.featured_big, 'crop': True, 'detail': True, }).url

    def get_featured_medium(self):
        return get_thumbnailer(self.featured_image).get_thumbnail({'size': (470, 180), 'box': self.featured_medium, 'crop': True, 'detail': True, }).url

    def get_featured_small(self):
        return get_thumbnailer(self.featured_image).get_thumbnail({'size': (170, 170), 'box': self.featured_small, 'crop': True, 'detail': True, }).url


class NewsCategory(models.Model):
    title = models.CharField("Título", max_length=90, help_text="Titulo da Categoria")
    slug = models.SlugField(max_length=200, blank=True, unique=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = u'Categoria de Notícia'
        verbose_name_plural = u'Categorias de Notícias'

    def __unicode__(self):
        return self.title


class ContestSubscriber(models.Model):
    # def update_filename(instance, filename):
    #     path = "uploads/concurso/"
    #     fname = filename.split('.')
    #     format = slugify(filename) + '.' + fname[-1]
    #     return os.path.join(path, format)
    name = models.CharField("Nome", max_length=140)
    cpf = models.CharField("CPF", max_length=15)
    address = models.CharField("Endereço", max_length=200)
    cep = models.CharField("CEP", max_length=200)
    phone = models.CharField("Telefone", max_length=200)
    email = models.EmailField()
    file = models.FileField("Arquivo declaração", upload_to='uploads/concurso/')
    work_file = models.FileField("Arquivo de trabalho", upload_to='uploads/concurso/')

    class Meta:
        verbose_name = u'Inscrição de concurso'
        verbose_name_plural = u'Inscrições de concurso'

    def __unicode__(self):
        return self.name


class News(models.Model):
    title = models.CharField("Título", max_length=90, help_text="Titulo da Noticia")
    subtitle = models.CharField("Sub-título", max_length=100, help_text="Para Manchetes", blank=True, null=True)
    text = RichTextUploadingField(verbose_name="Texto")
    slug = models.SlugField(max_length=200, blank=True)
    credit = models.CharField("Crédito", max_length=50, blank=True, help_text="Creditos da foto.")
    font = models.CharField("Fonte", max_length=50, blank=True, help_text="Fonte da notícia")
    author = models.CharField("Autor", max_length=50, blank=True, help_text="Autor da notícia")
    featured_image = models.ImageField("Imagem Destaque", upload_to='uploads/noticias/%Y/%m/', blank=True, help_text="Dimensões 600x335px ou maior - JPEG")
    featured_big = ImageRatioField('featured_image', '600x335', verbose_name='Destaque Grande', help_text="Destaque princial na home.")
    featured_medium = ImageRatioField('featured_image', '470x180', verbose_name='Destaque Médio', help_text="Destaque secundário home.")
    featured_small = ImageRatioField('featured_image', '170x170', verbose_name='Destaque Pequeno', help_text="Imagem para listagem de notícias e últimas noíticas.")
    published_at = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)
    user = models.ForeignKey(User, verbose_name='Usuário')
    status = models.BooleanField(verbose_name='Noticia Ativa?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver esta notícia")

apps/website/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import send_mail
from apps.website.models import ContestSubscriber


SUBJECT = {('Dúvida', 'Dúvida'),
          ('Informação', 'Informação'),
          ('Sugestão', 'Sugestão'),
          ('Reclamação', 'Reclamação'),
          ('Lei Geral', 'Lei Geral'),
          ('Empreendedor Individual', 'Empreendedor Individual'),
          ('Outros', 'Outros')}


class FormContact(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(max_length=50, required=True)
    subject = forms.ChoiceField(choices=SUBJECT, required=True)
    cnpj = forms.CharField(max_length=50, required=False)
    message = forms.Field(widget=forms.Textarea, required=True)

    def send(self):
        title = 'Mensagem do site Fenacon - Contato'
        target = 'fenacon@fenacon.org.br'
        text = """
        Nome: %(name)s
        E-mail: %(email)s
        Telefone: %(phone)s
        Assunto: %(subject)s
        CNPJ: %(cnpj)s
        Mensagem: %(message)s
        """ % self.cleaned_data

        send_mail(
            subject=title,
            message=text,
            from_email=target,
            recipient_list=[target],
            )


class ContestSubscriberForm(forms.ModelForm):
    class Meta:
        model = ContestSubscriber
        fields = ['name', 'email', 'address', 'cpf', 'cep', 'phone', 'file', 'work_file']

templates/website/concurso.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Fenacon - Prêmio Jubileu de Prata Fenacon 2016</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ MEDIA_URL }}vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{{ MEDIA_URL }}vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Theme CSS -->
    <link href="{{ MEDIA_URL }}css/agency.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
     function disableSubmit() {
      document.getElementById("submit").disabled = true;
     }

      function activateButton(element) {

          if(element.checked) {
            document.getElementById("submit").disabled = false;
           }
           else  {
            document.getElementById("submit").disabled = true;
          }

      }
    </script>
</head>

<body id="page-top" class="index" onload="disableSubmit()">

    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in"></div>
                <div class="intro-heading"></div>
                <!--<a href="#services" class="page-scroll btn btn-xl">Saiba mais</a>-->
            </div>
        </div>
    </header>

    <!-- Services Section -->
    <section id="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-street-view fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">A QUEM SE DESTINA</h4>
                    <p class="text-muted">Estudantes do ensino técnico, graduação e pós-graduação, profissionais contábeis e empresários do setor associados ao sistema FENACON, SESCON/SESCAP.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-trophy fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">PREMIAÇÃO</h4>
                    <p class="text-muted">Prêmio em dinheiro no valor de R$ 10.000,00 (dez mil reais), passagem e hospedagem para o evento de celebração 25 anos da FENACON no dia 23/11/2016 em Brasília-DF para o autor do projeto vencedor do concurso.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-info fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="service-heading">COMO PARTICIPAR</h4>
                    <p class="text-muted"><a href="{{ MEDIA_URL }}Regulamento_Premio_Jubileu_de_ Prata_Fenacon2016.pdf">Confira o regulamento</a> do concurso e inscreva seu projeto através do formulário abaixo.</p>
                </div>
            </div>

        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Inscreva-se</h2>
                    <h3 class="section-subheading text-muted">Preencha o formulário abaixo e envie sua inscrição.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form name="sentMessage" id="contactForm" novalidate method="post" action="{% url 'concurso' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Nome completo *" id="id_name" name="name" required data-validation-required-message="Por favor escreva seu nome.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Telefone *" id="id_phone" name="phone" required data-validation-required-message="Por favor escreva seu número de telefone.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="CPF *" id="id_cpf" name="cpf" required data-validation-required-message="Por favor escreva seu CPF.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="file" class="form-control" id="id_file" name="file" required data-validation-required-message="Por favor adicione um arquivo que comprove sua profissão (declaração de matrícula, diploma, comprovante de atuação ou declaração de associado).">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="E-mail *" id="id_email" name="email" required data-validation-required-message="Por favor escreva seu email.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Endereço *" id="id_address" name="address" required data-validation-required-message="Por favor escreva seu endereço.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="CEP *" id="id_cep" name="cep" required data-validation-required-message="Por favor escreva seu CEP.">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="file" class="form-control" id="id_work_file" name="work_file" required data-validation-required-message="Por favor adicione um arquivo de trabalho.">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <input type="checkbox" onchange="activateButton(this)" name=""> Li e aceito os termos do <a href="{{ MEDIA_URL }}Regulamento_Premio_Jubileu_de_ Prata_Fenacon2016.pdf" style="color:#666; text-decoration:underline;">Regulamento do Concurso</a>.</br></br>
                                <div id="success"></div>
                                <input type="submit" name="submit" id="submit" class="btn btn-xl" value="Enviar inscrição">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; FENACON.</span>
                </div>
                <div class="col-md-4">
                    <!--<ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>-->
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="{{ MEDIA_URL }}Regulamento_Premio_Jubileu_de_ Prata_Fenacon2016.pdf">Regulamento do concurso</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>




    <!-- jQuery -->
    <script src="{{ MEDIA_URL }}vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ MEDIA_URL }}vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="{{ MEDIA_URL }}js/jqBootstrapValidation.js"></script>
    <script src="{{ MEDIA_URL }}js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="{{ MEDIA_URL }}js/agency.min.js"></script>

</body>

</html>

templates/website/evento.html
{% extends 'elements/base.html' %}
{% block title %}{{ object.title }} - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">

                <div class="row">
                    <div class="large-12 medium-12 small-12 columns">
                       <div class="articleConteudo">
                           <article>
                               <div id="articleTitle">
                                  <h3>{{ object.title }}</h3>
                               </div>

                               <div class="articleTexto">
                                    <ul class="list-event-info">
                                        {% if object.city %}
                                        <li>
                                            <span>Cidade/Estado: </span>
                                            <p>{{ object.city }}</p>
                                        </li>
                                        {% endif %}
                                        <li>
                                            <span>Local:</span>
                                            <p>{{ object.local }}</p>
                                        </li>
                                        <li>
                                            <span>Inicio:</span>
                                            <p>{{ object.start_at }}</p>
                                        </li>
                                         <li>
                                            <span>Término:</span>
                                            <p>{{ object.ends_in }}</p>
                                        </li>
                                    </ul>

                                    {{ object.text|safe }}

                               </div>

                               <div class="social">
                                 <!-- Go to www.addthis.com/dashboard to customize your tools -->
                                 <div class="addthis_sharing_toolbox"></div>
                               </div>



                              <div class="row">
                                  <div class="large-12 medium-12 columns">

                                       <h5>Comente »</h5>
                                     <div class="comentarios mobile-off">
                                        <div class="fb-comments" data-href="http://www.fenacon.org.br/{{ request.get_full_path }}" data-width="700" data-numposts="2" data-colorscheme="light"></div>
                                     </div>
                                  </div>
                              </div>

                              <hr>
                           </article>
                       </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/website/press_clipping.html
{% extends 'elements/base.html' %}
{% block title %}{{ object.title }} - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">{{ object.title }}</h2>
                <div class="row">
                    <div class="large-12 medium-12 small-12 columns">
                        {{ object.text|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}