fenacon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.flatpages.views import (ActingDetailView, InstitutionalDetailView,
                                  AnnounceView)
from apps.office.views import SyndicateListView, OfficeListView
from apps.website.views import HomeView, SearchView
from apps.website.api import (api_root, NewsListAPI, NewsCategoryListAPI,
                              EventListAPI, PressClippingListAPI,
                              CreateUserAPI, FenaconMidiaListAPI,
                              SyndicateListAPI, OfficeListAPI, AboutUsListAPI,
                              ObtainAuthToken, MagazineListAPI,
                              PressClippingAPI, NewsDetailAPI)
from fenacon import settings

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^', include('apps.website.urls')),
    url(r'^multimidia/', include('apps.multimidia.urls')),
    url(r'^busca/', SearchView.as_view(), name='search'),
    url(r'^sindicatos-filiados/', SyndicateListView.as_view(), name='syndicate'),
    # url(r'^escritorios/', OfficeListView.as_view(), name='offices'),
    url(r'^atuacao/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', ActingDetailView.as_view(), name='acting_detail'),
    url(r'^institucional/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', InstitutionalDetailView.as_view(), name='institutional_detail'),
    url(r'^publicacoes/(?P<slug>[\w_-]+)/', AnnounceView.as_view(), name='announce_detail'),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += [
    url(r'^api/$', api_root),
    url(r'^api/token-auth/', ObtainAuthToken.as_view()),
    url(r'^api/news/$', NewsListAPI.as_view(), name='news_list_api'),
    url(r'^api/news/(?P<pk>\d+)/?$', NewsDetailAPI.as_view(),
        name='news_detail_api'),
    url(r'^api/events/$', EventListAPI.as_view(), name='event_list_api'),
    url(r'^api/category/$', NewsCategoryListAPI.as_view(),
        name='category_list_api'),
    url(r'^api/user/create/$', CreateUserAPI.as_view(),
        name='user_create_api'),
    url(r'^api/press-clipping/$', PressClippingListAPI.as_view(),
        name='pressclipping_list_api'),
    url(r'^api/press-clipping/(?P<pk>\d+)/?$', PressClippingAPI.as_view(),
        name='pressclipping_detail_api'),
    url(r'^api/fenacon-midia/$', FenaconMidiaListAPI.as_view(),
        name='fenaconmidia_list_api'),
    url(r'^api/syndicate/$', SyndicateListAPI.as_view(),
        name='syndicate_list_api'),
    url(r'^api/office/$', OfficeListAPI.as_view(),
        name='office_list_api'),
    url(r'^api/about-us/$', AboutUsListAPI.as_view(),
        name='aboutus_list_api'),
    url(r'^api/magazine/$', MagazineListAPI.as_view(),
        name='magazine_list_api'),
]

urlpatterns += patterns('',
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^ckeditor/', include('ckeditor_uploader.urls')),
)

admin.site.site_header = 'FENACON Website'

apps/website/models.py
# coding=utf-8
from datetime import datetime
from apps.accounts.models import User
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify
from easy_thumbnails.files import get_thumbnailer
from image_cropping import ImageRatioField
from ckeditor_uploader.fields import RichTextUploadingField
import requests

REGION = {('norte', 'Norte'),
          ('nordeste', 'Nordeste'),
          ('centro-oeste', 'Centro-Oeste'),
          ('sudeste', 'Sudeste'),
          ('sul', 'Sul')}

UF_CHOICES = (
    ('', 'Nacional'),
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins')
)


class SocialNetwork(models.Model):
    facebook = models.URLField(null=True, blank=True)
    instagram = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    youtube = models.URLField(null=True, blank=True)
    telefax = models.CharField(null=True, blank=True, max_length=30)
    address = models.CharField('Endereço FENACON', null=True, blank=True, max_length=200)
    cep = models.CharField('CEP da FENACON', null=True, blank=True, max_length=200)
    address_imprensa = models.CharField('Endereço Assessoria', null=True, blank=True, max_length=200)
    cep_imprensa = models.CharField('CEP Assessoria', null=True, blank=True, max_length=200)
    phone = models.CharField('Telefones Assessoria', null=True, blank=True, max_length=30)
    email = models.EmailField("Email da asessoria de impresa", null=True, blank=True)

    def __unicode__(self):
        return 'Contato FENACON'

    class Meta:
        verbose_name = "Contato"
        verbose_name_plural = "Contato"


class Banner(models.Model):
    photo = models.ImageField('Foto', upload_to='uploads/banner/', blank=True, null=True, help_text="Dimensões 870x135px")
    link = models.URLField(help_text="Endereço da página", blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='Data do Cadastro', blank=True, default=datetime.now)
    start_at = models.DateTimeField(verbose_name='Começa em', default=datetime.now)
    ends_in = models.DateTimeField(verbose_name='Términa em')
    user = models.ForeignKey(User, verbose_name='Usuário')
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'

    def __unicode__(self):
        return u'%s' % str(self.photo).split('/')[-1]


class Institute(models.Model):
    name = models.CharField("Nome", max_length=90)
    description = models.CharField("Descrição", max_length=140)
    link = models.URLField(help_text="Endereço da página")
    featured_image = models.ImageField("Imagem", upload_to='uploads/instituto/%Y/%m/', help_text="Dimensões 275x70px")
    status = models.BooleanField(verbose_name='Ativo?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver este instituição.")
    user = models.ForeignKey(User, verbose_name='Usuário')

    class Meta:
        verbose_name = u'Instituto Fenacon'
        verbose_name_plural = u'Institutos Fenacon'

    def __unicode__(self):
        return self.name


class ContributionGuide(models.Model):
    link = models.URLField(help_text="Endereço da página")
    status = models.BooleanField(verbose_name='Ativo?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver este instituição.")

    class Meta:
        verbose_name = u'Guia de contribuição sindical'
        verbose_name_plural = u'Guia de contribuição sindical'

    def __unicode__(self):
        return self.link


class Event(models.Model):
    title = models.CharField("Título", max_length=90, help_text="Titulo do Evento")
    text = RichTextUploadingField(verbose_name="Texto", null=True, blank=True)
    slug = models.SlugField(max_length=200, blank=True)
    city = models.CharField('Cidade/Estado', max_length=50, null=True, blank=True)
    local = models.CharField('Endereço', max_length=150)
    region = models.CharField('Região', max_length=50, choices=REGION, null=True, blank=True)
    credit = models.CharField("Crédito", max_length=30, blank=True, help_text="Creditos da foto.")
    featured_image = models.ImageField("Imagem Destaque", null=True, blank=True, upload_to='uploads/eventos/%Y/%m/', help_text="Dimensões 600x335 ou maior - JPEG")
    featured_big = ImageRatioField('featured_image', '600x335', verbose_name='Destaque Grande', help_text="Destaque princial na home.")
    featured_medium = ImageRatioField('featured_image', '470x180', verbose_name='Destaque Médio', help_text="Destaque secundário home.")
    featured_small = ImageRatioField('featured_image', '170x170', verbose_name='Destaque Pequeno', help_text="Imagem para listagem de eventos.")
    published_at = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)
    start_at = models.DateTimeField(verbose_name='Começa em', default=datetime.now)
    ends_in = models.DateTimeField(verbose_name='Términa em')
    status = models.BooleanField(verbose_name='Evento Ativo?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver este evento.")
    main_featured = models.BooleanField(verbose_name='Destaque principal', default=False, help_text="Coloca a notícia em destaque. Deve possuir imagem destaque.")
    featured = models.BooleanField(verbose_name='Destaque secundário', default=False, help_text="Coloca a notícia em destaque. Deve possuir imagem destaque.")
    user = models.ForeignKey(User, verbose_name='Usuário')


    class Meta:
        ordering = ('-published_at',)
        verbose_name = u'Evento'
        verbose_name_plural = u'Eventos'
        get_latest_by = 'published_at'

    @models.permalink
    def get_absolute_url(self):
        return ('event_detail', [self.slug, self.pk])

    def __unicode__(self):
        return self.title

    def get_featured_big(self):
        return get_thumbnailer(self.featured_image).get_thumbnail({'size': (600, 335), 'box': self.featured_big, 'crop': True, 'detail': True, }).url

    def get_featured_medium(self):
        return get_thumbnailer(self.featured_image).get_thumbnail({'size': (470, 180), 'box': self.featured_medium, 'crop': True, 'detail': True, }).url

    def get_featured_small(self):
        return get_thumbnailer(self.featured_image).get_thumbnail({'size': (170, 170), 'box': self.featured_small, 'crop': True, 'detail': True, }).url


class NewsCategory(models.Model):
    title = models.CharField("Título", max_length=90, help_text="Titulo da Categoria")
    slug = models.SlugField(max_length=200, blank=True, unique=True)
    status = models.BooleanField(default=True)

    class Meta:
        verbose_name = u'Categoria de Notícia'
        verbose_name_plural = u'Categorias de Notícias'

    def __unicode__(self):
        return self.title


class ContestSubscriber(models.Model):
    # def update_filename(instance, filename):
    #     path = "uploads/concurso/"
    #     fname = filename.split('.')
    #     format = slugify(filename) + '.' + fname[-1]
    #     return os.path.join(path, format)
    name = models.CharField("Nome", max_length=140)
    cpf = models.CharField("CPF", max_length=15)
    address = models.CharField("Endereço", max_length=200)
    cep = models.CharField("CEP", max_length=200)
    phone = models.CharField("Telefone", max_length=200)
    email = models.EmailField()
    file = models.FileField("Arquivo declaração", upload_to='uploads/concurso/')
    work_file = models.FileField("Arquivo de trabalho", upload_to='uploads/concurso/')

    class Meta:
        verbose_name = u'Inscrição de concurso'
        verbose_name_plural = u'Inscrições de concurso'

    def __unicode__(self):
        return self.name


class News(models.Model):
    title = models.CharField("Título", max_length=90, help_text="Titulo da Noticia")
    subtitle = models.CharField("Sub-título", max_length=100, help_text="Para Manchetes", blank=True, null=True)
    text = RichTextUploadingField(verbose_name="Texto")
    slug = models.SlugField(max_length=200, blank=True)
    credit = models.CharField("Crédito", max_length=50, blank=True, help_text="Creditos da foto.")
    font = models.CharField("Fonte", max_length=50, blank=True, help_text="Fonte da notícia")
    author = models.CharField("Autor", max_length=50, blank=True, help_text="Autor da notícia")
    featured_image = models.ImageField("Imagem Destaque", upload_to='uploads/noticias/%Y/%m/', blank=True, help_text="Dimensões 600x335px ou maior - JPEG")
    featured_big = ImageRatioField('featured_image', '600x335', verbose_name='Destaque Grande', help_text="Destaque princial na home.")
    featured_medium = ImageRatioField('featured_image', '470x180', verbose_name='Destaque Médio', help_text="Destaque secundário home.")
    featured_small = ImageRatioField('featured_image', '170x170', verbose_name='Destaque Pequeno', help_text="Imagem para listagem de notícias e últimas noíticas.")
    published_at = models.DateTimeField(verbose_name='Data de Publicacao', default=datetime.now)
    user = models.ForeignKey(User, verbose_name='Usuário')
    status = models.BooleanField(verbose_name='Noticia Ativa?', default=True, help_text="Se esta opção estiver desmarcada os usuários do portal não irão mais ver esta notícia")

templates/elements/base.html
<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1" />
    <meta name="author" content="" />
    <meta name="copyright" content="" />
    <meta name="robots" content="all" />
    <meta name="revisit-after" content="1 days" />
    <meta name="Keywords" content="" />
    <meta name="google-site-verification" content="">
    <meta http-equiv="X-UA-Compatible" content="IT=edge,chrome=IE8">
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta name="application-name" content="">
    <meta name="description" content="">
    <meta property="og:title" content="">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="og:description" content="">
    <meta property="fb:app_id" content="1646697235569741" />
    <title>{% block title %}{% endblock %}Fenacon</title>

     <!-- IOS -->
    <link rel="apple-touch-icon" sizes="57x57" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ MEDIA_URL }}img/icons/icon/apple-icon-180x180.png">

    <!-- Android -->
    <link rel="icon" type="image/png" sizes="192x192"  href="{{ MEDIA_URL }}img/icons/icon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ MEDIA_URL }}img/icons/icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ MEDIA_URL }}img/icons/icon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ MEDIA_URL }}img/icons/icon/favicon-16x16.png">
    <link rel="manifest" href="{{ MEDIA_URL }}img/icons/icon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ MEDIA_URL }}img/icons/icon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">


    <link rel="stylesheet" href="{{ MEDIA_URL }}css/font-awesome.min.css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/slick.min.css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/fancybox.min.css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/jquery-ui.min.css" />

    <link rel="stylesheet" href="{{ MEDIA_URL }}css/foundation.min.css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/app.min.css" />
    {% block extracss %}{% endblock %}
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.4&appId=964698416916163";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <!-- end block css -->
    <script src="{{ MEDIA_URL }}js/vendor/modernizr.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1514421771999659');
        fbq('track', 'PageView');
    </script>
    <noscript>
        <img height="1" width="1" src="https://www.facebook.com/tr?id=1514421771999659&ev=PageView&noscript=1"/>
    </noscript>
    <!-- End Facebook Pixel Code -->

</head>

<body class="antialiased">
    <div id="body">
        {% include 'elements/header.html' %}
        <section class="main">
            {% block content %}{% endblock %}
        </section>
        {% include 'elements/footer.html' %}
    </div>
    <!-- block scripts -->
    <script src="{{ MEDIA_URL }}js/vendor/jquery.min.js"></script>
    <script src="{{ MEDIA_URL }}js/foundation.min.js"></script>
    <script src="{{ MEDIA_URL }}js/slick.min.js"></script>
    <script src="{{ MEDIA_URL }}js/fancybox.min.js"></script>
    <script src="{{ MEDIA_URL }}js/jquery-ui.min.js"></script>
    <script src="{{ MEDIA_URL }}js/script.min.js"></script>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-561d4598ecd86a93" async="async"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-31720619-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-31720619-2');
    </script>
    {% block extrajs %}{% endblock %}
    <!-- end block scripts -->
</body>

</html>

templates/elements/footer.html
<footer>
    <div class="footer">
        <div class="row">

            <div class="large-6 medium-6 small-12 columns">
                <h4>contato</h4>
                <p>Telefax: {{ contact.telefax }}</p>
                <p>Fenacon - Federação Nacional das Empresas de Serviços Contábeis e das Empresas de Assessoramento, Perícias, Informações e Pesquisas.</p>
                <p>{{ contact.address }}, CEP {{ contact.cep }}</p>

                        



            </div>
            <div class="large-4 medium-4 small-12 columns">
                <h4>redes sociais</h4>
                <ul class="social-list">
                    {% if contact.facebook %}
                    <li>
                        <a class="fa fa-facebook" href="{{ contact.facebook }}"></a>
                    </li>
                    {% endif %}
                    {% if contact.instagram %}
                    <li>
                        <a class="fa fa-instagram" href="{{ contact.instagram }}"></a>
                    </li>
                    {% endif %}
                    {% if contact.twitter %}
                    <li>
                        <a class="fa fa-twitter" href="{{ contact.twitter }}"></a>
                    </li>
                    {% endif %}
                    {% if contact.youtube %}
                    <li>
                        <a class="fa fa-youtube" href="{{ contact.youtube }}"></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div class="large-2 medium-2 small-12 columns">
                <h4>atendimento</h4>
                <div style="text-align: center; margin-top: -17px;">
                <!--    <a href="http://www.fenacondigital.org.br/digital/central/admin/ouvidoria.aspx?ativa=24-8b-68-9b-de-41-fd-d1&enquadramento=s?entidadeativa=3"><img width="90px" height="90px" src="{{MEDIA_URL}}img/icons/contato.png"></a> -->
                   <a href="mailto:contato@fenacon.org.br" style="color:white;">contato@fenacon.org.br</a>
                </div>
            </div>
        </div>

    </div>
    <div class="copyright">
        <div class="row">
            <div class="large-12 medium-12 small-12 columns text-center">
                <p>2015 © Copyright. Todos os direitos reservados/ Desenvolvido por <a href="http://cafeepixel.com.br/" target="_blank">Café e Pixel</a></p>
            </div>
        </div>
    </div>
</footer>

templates/elements/header.html
<header class="nav-header">
    <div id="menu-show-mobile"><i class="fa fa-bars"></i></div>
    <div class="logobar">
        <div class="row">
            <div class="large-4 medium-4 small-12 columns">
                <div class="menu-logo">
                    <a href="{% url 'home' %}" class="logo">
                        <img src="{{ MEDIA_URL }}img/icons/fenacon_logo.png" height="95" width="339" alt="">
                    </a>
                </div>
            </div>
            <div class="large-4 medium-4 small-12 columns">
                <form action="{% url 'search' %}" class="form-search" method="get">
                    <input type="text" name="q" id="id_q" placeholder="Buscar no site">
                    <button type="submit" class="btn-search"><i class="fa fa-search"></i></button>
                </form>
            </div>
        </div>
    </div>
    <div class="navbar">
        <div class="row">
            <div class="large-12 medium-12 small-12 columns">
                <nav class="menu">
                    <ul>
                        <li class="dropdown">
                            <a href="#">Institucional <i class="fa fa-angle-double-down"></i> </a>
                            <ul class="dropdown-list">
                                {% for item in institutional_list %}
                                <li><a href="{% url 'institutional_detail' item.slug item.pk %}">{{ item.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#">Atuação <i class="fa fa-angle-double-down"></i></a>
                            <ul class="dropdown-list">
                                {% for page in acting_list %}
                                <li><a href="{% url 'acting_detail' page.slug page.pk %}">{{ page.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#">Notícias <i class="fa fa-angle-double-down"></i></a>
                            <ul class="dropdown-list">
                                <li><a href="{% url 'news_list' %}">Todas as Notícias</a></li>
                                <li><a href="{% url 'fenaconmidia_list' %}">FENACON na Mídia</a></li>
                                <li><a href="{% url 'pressclipping_list' %}">Press Clipping</a></li>
                                <li><a href="{% url 'news_list' %}?category=rede-de-noticias">Rede de Notícias</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#">Publicações <i class="fa fa-angle-double-down"></i></a>
                            <ul class="dropdown-list">
                                <li><a href="{% url 'magazines' %}">Revista FENACON</a></li>
                                <li><a href="{% url 'publications' %}">Outras Publicações</a></li>
                                {% if announce %}
                                <li><a href="{% url 'announce_detail' announce.slug %}">Como anunciar</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#">Multimídia <i class="fa fa-angle-double-down"></i></a>
                            <ul class="dropdown-list">
                                <li><a href="{% url 'videos' %}">Vídeos</a></li>
                            </ul>
                        </li>

                        <li><a href="{% url 'event_list' %}">Eventos</a></li>
                        <li><a href="{% url 'syndicate' %}">Sindicatos Filiados</a></li>
<!--                        <li><a href="http://www.fenacondigital.org.br/digital/central/admin/ouvidoria.aspx?ativa=24-8b-68-9b-de-41-fd-d1&enquadramento=s?entidadeativa=3" target="_blank">Atendimento</a></li>-->
			<li><a href="http://extranet.fenacon.org.br/">Extranet</a></li>

                    </ul>
                </nav>

            </div>
        </div>
    </div>
</header>