fenacon/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.flatpages.views import (ActingDetailView, InstitutionalDetailView,
                                  AnnounceView)
from apps.office.views import SyndicateListView, OfficeListView
from apps.website.views import HomeView, SearchView
from apps.website.api import (api_root, NewsListAPI, NewsCategoryListAPI,
                              EventListAPI, PressClippingListAPI,
                              CreateUserAPI, FenaconMidiaListAPI,
                              SyndicateListAPI, OfficeListAPI, AboutUsListAPI,
                              ObtainAuthToken, MagazineListAPI,
                              PressClippingAPI, NewsDetailAPI)
from fenacon import settings

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^', include('apps.website.urls')),
    url(r'^multimidia/', include('apps.multimidia.urls')),
    url(r'^busca/', SearchView.as_view(), name='search'),
    url(r'^sindicatos-filiados/', SyndicateListView.as_view(), name='syndicate'),
    # url(r'^escritorios/', OfficeListView.as_view(), name='offices'),
    url(r'^atuacao/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', ActingDetailView.as_view(), name='acting_detail'),
    url(r'^institucional/(?P<slug>[\w_-]+)-(?P<pk>\d+)/', InstitutionalDetailView.as_view(), name='institutional_detail'),
    url(r'^publicacoes/(?P<slug>[\w_-]+)/', AnnounceView.as_view(), name='announce_detail'),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += [
    url(r'^api/$', api_root),
    url(r'^api/token-auth/', ObtainAuthToken.as_view()),
    url(r'^api/news/$', NewsListAPI.as_view(), name='news_list_api'),
    url(r'^api/news/(?P<pk>\d+)/?$', NewsDetailAPI.as_view(),
        name='news_detail_api'),
    url(r'^api/events/$', EventListAPI.as_view(), name='event_list_api'),
    url(r'^api/category/$', NewsCategoryListAPI.as_view(),
        name='category_list_api'),
    url(r'^api/user/create/$', CreateUserAPI.as_view(),
        name='user_create_api'),
    url(r'^api/press-clipping/$', PressClippingListAPI.as_view(),
        name='pressclipping_list_api'),
    url(r'^api/press-clipping/(?P<pk>\d+)/?$', PressClippingAPI.as_view(),
        name='pressclipping_detail_api'),
    url(r'^api/fenacon-midia/$', FenaconMidiaListAPI.as_view(),
        name='fenaconmidia_list_api'),
    url(r'^api/syndicate/$', SyndicateListAPI.as_view(),
        name='syndicate_list_api'),
    url(r'^api/office/$', OfficeListAPI.as_view(),
        name='office_list_api'),
    url(r'^api/about-us/$', AboutUsListAPI.as_view(),
        name='aboutus_list_api'),
    url(r'^api/magazine/$', MagazineListAPI.as_view(),
        name='magazine_list_api'),
]

urlpatterns += patterns('',
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    (r'^ckeditor/', include('ckeditor_uploader.urls')),
)

admin.site.site_header = 'FENACON Website'

apps/website/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.mail import send_mail
from apps.website.models import ContestSubscriber


SUBJECT = {('Dúvida', 'Dúvida'),
          ('Informação', 'Informação'),
          ('Sugestão', 'Sugestão'),
          ('Reclamação', 'Reclamação'),
          ('Lei Geral', 'Lei Geral'),
          ('Empreendedor Individual', 'Empreendedor Individual'),
          ('Outros', 'Outros')}


class FormContact(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(max_length=50, required=True)
    subject = forms.ChoiceField(choices=SUBJECT, required=True)
    cnpj = forms.CharField(max_length=50, required=False)
    message = forms.Field(widget=forms.Textarea, required=True)

    def send(self):
        title = 'Mensagem do site Fenacon - Contato'
        target = 'fenacon@fenacon.org.br'
        text = """
        Nome: %(name)s
        E-mail: %(email)s
        Telefone: %(phone)s
        Assunto: %(subject)s
        CNPJ: %(cnpj)s
        Mensagem: %(message)s
        """ % self.cleaned_data

        send_mail(
            subject=title,
            message=text,
            from_email=target,
            recipient_list=[target],
            )


class ContestSubscriberForm(forms.ModelForm):
    class Meta:
        model = ContestSubscriber
        fields = ['name', 'email', 'address', 'cpf', 'cep', 'phone', 'file', 'work_file']

templates/contato.html
{% extends 'elements/base.html' %}
{% block title %}Contato - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">Fale conosco</h2>
                {% if messages %}
                <div class="row">
                    <div class="large-12 medium-12 small-12 columns ">
                        {% for message in messages %}
                          <div data-alert class="alert-box {{ message.tags }} radius">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                          </div>
                        {% endfor %}
                    </div>
                 </div>
                {% endif %}
                <div class="row">
                    <div class="large-6 medium-6 small-12 columns">
                        <form class="contatos" accept-charset="utf-8" method="post" action="{% url 'contact' %}" data-abide>
                            {% csrf_token %}
                            <div class="row">
                                <div class="large-12 medium-12 columns">
                                    <label>Seu nome
                                        <small>*</small>
                                        {{ form.name }}
                                    </label>
                                    <small class="error">Digite seu nome</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="large-6 medium-6 columns">
                                    <label>Seu email
                                        <small>*</small>
                                        {{ form.email }}
                                    </label>
                                    <small class="error">Digite seu email</small>
                                </div>
                                <div class="large-6 medium-6 columns">
                                    <label>Seu telefone
                                        <small>*</small>
                                        {{ form.phone }}
                                    </label>
                                    <small class="error">Digite seu telefone</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="large-6 medium-6 columns">
                                    <label>CNPJ
                                        {{ form.cnpj }}
                                    </label>
                                </div>
                                <div class="large-6 medium-6 small-12 columns">
                                    <label>Assunto
                                        <small>*</small>
                                        <select id="id_subject" name="subject" aria-invalid="false">
                                        <option value="Dúvida">Dúvida</option>
                                        <option value="Empreendedor Individual">Empreendedor Individual</option>
                                        <option value="Sugestão">Sugestão</option>
                                        <option value="Reclamação">Reclamação</option>
                                        <option value="Lei Geral">Lei Geral</option>
                                        <option value="Informação">Informação</option>
                                        <option value="Outros">Outros</option>
                                        </select>
                                    </label>
                                    <small class="error">Digite o assunto</small>
                                </div>
                            </div>
                             <div class="row">
                                <div class="large-12 medium-12 small-12 columns">
                                    <label>Mensagem
                                        <small>*</small>
                                        {{ form.message }}
                                    </label>
                                    <small class="error">Digite o assunto</small>
                                </div>
                            </div>
                            <button type="submit" class="button small  round">Enviar</button>
                        </form>
                    </div>
                    <div class="large-6 medium-6 small-12 columns">
                        <div class="contact-map">
                            <b>Contato</b>
                            <p>Fenacon- Federação Nacional das Empresas de Serviços Contábeis e das Empresas de Assessoramento, Perícias, Informações e Pesquisas.</p>
                            <p>
                                {{ contact.address }}
                                <br> CEP: {{ contact.cep }}
                                <br> Telefax: {{ contact.telefax }}
                            </p>
                            {% if contact.address_imprensa or contact.cep_imprensa or contact.phone or contact.email %}
                            <b>Asessoria de Imprensa</b>
                            <p>
                                {% if contact.address_imprensa %}{{ contact.address_imprensa }}{% endif %}
                                {% if contact.cep_imprensa %}<br> CEP: {{ contact.cep_imprensa }}{% endif %}
                                {% if contact.phone %}<br> Telefone: {{ contact.phone }}{% endif %}
                                {% if contact.email %}<br> Email: <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>{% endif %}
                            </p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/flat-page.html
{% extends 'elements/base.html' %}
{% block title %}{{ object.title }} - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">{{ object.title }}</h2>
                <div class="row">
                    <div class="large-12 medium-12 small-12 columns">
                        {{ object.text|safe }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/listagem-busca.html
{% extends 'elements/base.html' %}
{% block title %}Resultados para "{{ request.GET.q }}" - {% endblock %}
{% block content %}
<section class="block">
    <div class="last-news">
        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">{{ news.count }} Resultados para "{{ request.GET.q }}" em notícias</h2>

                <div class="row">
                    <div class="large-12 medium-12 small-12 columns">
                        <ul class="small-block-grid-1 medium-block-grid-1 large-block-grid-1">
                            {% for object in news %}
                            <li>
                                <div class="item-list-news">
                                    <div class="row">
                                        <div class="large-2 medium-3 small-12 columns">
                                            <div class="img-list-news">
                                                <a href="{{ object.get_absolute_url }}">
                                                    {% if object.featured_image %}
                                                    <img src="{{ object.get_featured_small }}" height="170" width="170" alt="">
                                                    {% else %}
                                                    <img src="{{ MEDIA_URL }}img/icons/news-default.jpg" height="170" width="170" alt="">
                                                    {% endif %}
                                                </a>
                                            </div>
                                        </div>
                                        <div class="large-10 medium-9 small-12 columns">
                                            <div class="info-list-news">
                                                 <b>{{ object.published_at }}</b>
                                                <a href="{{ object.get_absolute_url }}"><h4>{{ object.title }}</h4></a>
                                                <p>{{ object.subtitle }}</p>
                                                <a href="{{ object.get_absolute_url }}" class="button small round">Ver mais</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">{{ videos.count }} Resultados para "{{ request.GET.q }}" em vídeos</h2>

                <div class="row">
                    <div class="large-12 medium-12 small-12 columns">
                        <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-2">
                           {% for video in videos %}
                               <li>
                                   <div class="item-video">
                                        <div class="iframe-video">
                                            {% if video.type == '0' %}
                                            <iframe src="https://player.vimeo.com/video/{{ video.embed_code }}" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                                            {% elif video.type == '1' %}
                                            <iframe width="1280" height="720" src="https://www.youtube.com/embed/{{ video.embed_code }}?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
                                            {% endif %}
                                        </div>

                                        <h3>{{ video.title }}</h3>
                                        <p class="categoria">{{ video.category }}</p>
                                   </div>
                               </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="small-12 columns">
                <h2 class="section-title text-left">{{ publications.count }} Resultados para "{{ request.GET.q }}" em publicações</h2>
                <div class="row">
                    <div class="large-12 medium-12 small-12 columns">
                       <ul class="list-magazines small-block-grid-2 medium-block-grid-4 large-block-grid-6">
                          {% for magazine in publications %}
                            <li>
                                <div class="item-magazine">
                                    <div class="cover">
                                        <img src="{{ MEDIA_URL }}{{ magazine.image }}" height="" width="" alt="">
                                    </div>
                                    <div class="name">
                                        <h5>{{ magazine.number }}</h5>
                                    </div>
                                    <div class="actions">
                                        <a href="{{ MEDIA_URL }}{{ magazine.file }}" target="_blank">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                        <a href="{{ MEDIA_URL }}{{ magazine.file }}" download>
                                            <i class="fa fa-download"></i>
                                        </a>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                       </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>

{% endblock %}